### ISSUE TITLE
Vdom bug

### ISSUE THREAD

**Issue by IwanKaramazow** [OvermindDL1/bucklescript-tea#11]
**Minimal case**
```ocaml
type msg' = 
   | Trigger
   [@@bs.deriving {accessors}]

type model = (string option * string option)

let update' model = function
  | Trigger ->
    let (left, _) = model in
    (left, Some "right")
  
let render_model = function 
  | (Some _, Some _) ->
      input' [value "This should be on screen"] []
  | _ -> 
    span [] [text "nothing"]

let view' model =
  div []
    [ button [onClick Trigger] [text "trigger rerender"]
    ; render_model model
    ]

let main =
  beginnerProgram {
    model = (Some "left", None);
    update = update';
    view = view'
  }
```

**Starting state**
![captura de pantalla 2017-02-10 a las 16 19 21](https://cloud.githubusercontent.com/assets/10634678/22832041/ca59ed28-efac-11e6-88ad-146bf7b2310c.png)

**Expected**
Whenever I click the button, it should render a `input` with `This should be on screen` as value.
![captura de pantalla 2017-02-10 a las 16 19 29](https://cloud.githubusercontent.com/assets/10634678/22832045/d0ac0cc4-efac-11e6-98b8-9c60c19a7470.png)

**Actual**
Whenever I click the button, it renders an empty span instead of the `input`.
![captura de pantalla 2017-02-10 a las 16 19 00](https://cloud.githubusercontent.com/assets/10634678/22832051/d50ad9b2-efac-11e6-9be3-6c81a4bf34e8.png)

If I wrap `input` inside `render_model`  in an extra `div`, it renders correctly. I think this might be a bug in the vdom diffing? I noticed that using `noNode` instead of `span [] []` in the catch-all case of `render_model`, fixes this

**Comment by OvermindDL1** [comment]
Ahhh, fascinating that it would do that, I'll examine shortly.

Also a note, the `[@@bs.deriving {accessors}]` annotation goes on types, not function definitions, it does nothing there.  :-)

Also, where is your `Trigger` type defined?  o.O

**Comment by IwanKaramazow** [comment]
I think that something went wrong while copy pasting into github. Updated the attributes & trigger type.

**Comment by OvermindDL1** [comment]
Heh, no worry, I fixed it in b04c815d51ea1d66c5f96514fd1f50c7c686d379.  It was entirely my fault, I had the new code here but forgot to commit it back to github a few days ago.  ^.^

Pushing a new NPM update too, just a couple minutes.  :-)

**Comment by OvermindDL1** [comment]
Version 0.2.1 is up.

**Comment by IwanKaramazow** [comment]
Muchas gracias!
