### ISSUE TITLE
Ideal way to integrate TEA into ReasonReact

### ISSUE THREAD

**Issue by BenSchZA** [OvermindDL1/bucklescript-tea#121]
Using the Reason TEA example, I used the following code with the example code in order to create a ReasonReact element with TEA code for the logic, view etc. Is this the right way to do this? It works, but not sure how you'd send React props to the element.

```
^^^ TEA Reason code above ^^^

let component = ReasonReact.statelessComponent("Tea");

let make = _children => {
  ...component,
  render: _self =>
    <div id="Tea">
      <script>
        [%bs.raw {| 
          setTimeout(function(){
            main(document.getElementById("Tea"));
          }, 1)
        |}]
      </script>
    </div>
}
```

**Comment by BenSchZA** [comment]
So this is the updated version I ended up with. 

The issue now is that the interface has type 
```Tea_app.programInterface(msg)
type programInterface('msg) = Js.t(
  < pushMsg : 'msg -> unit >
)```
By logging the interface object to the browser console I can call `pushMsg` to increment and decrement the counter successfully, but I'm not sure how to call it from within the ReasonML React component.

```
type document; /* abstract type for a document object */
[@bs.send] external getElementById: (document, string) => Js.null_undefined(Web.Node.t) = "getElementById";
[@bs.val] external doc: document = "document";
[@bs.module "./Tea.bs.js"] external programInterface: Js.null_undefined(Web.Node.t) => Tea_app.programInterface(msg) = "main";

type action = RenderMain;
type state = Start | Initialized;

let component = ReasonReact.reducerComponent("Tea");
let make = _children => {
  ...component,
  initialState: _state => Start,
  reducer: (action, _state) =>
    switch (action) {
      | RenderMain => {
        let interface = programInterface(getElementById(doc, "Tea"));
        Js.log(interface##pushMsg);
        ReasonReact.Update(Initialized);
      }
    },
  didMount: self => self.send(RenderMain),
  render: _self => <div id="Tea" />
}
```

**Comment by BenSchZA** [comment]
Found these two types which will help with the interfacing:

```
type beginnerProgram('model, 'msg) = {
  model: 'model,
  update: ('model, 'msg) => 'model,
  view: 'model => Vdom.t('msg),
};
type programInterface('msg) = {. "pushMsg": 'msg => unit};
```

**Comment by BenSchZA** [comment]
Ended up solving the issue using the following. This isn't really an issue anymore, but maybe I can include this in some documentation somewhere? I know this repo isn't specific to Reason or ReasonReact though, but someone else might need to do something similar.

```
type document; /* abstract type for a document object */
[@bs.send] external getElementById: (document, string) => Js.null_undefined(Web.Node.t) = "getElementById";
[@bs.val] external doc: document = "document";

type action = RenderMain;
type state = Start | Initialized;

let component = ReasonReact.reducerComponent("Tea");
let make = _children => {
  ...component,
  initialState: _state => Start,
  reducer: (action, _state) =>
    switch (action) {
      | RenderMain => {
        let interface = main(getElementById(doc, "Tea"));
        let pushMsg = interface()##pushMsg;
        pushMsg(Reset);
        ReasonReact.Update(Initialized);
      }
    },
  didMount: self => self.send(RenderMain),
  render: _self => <div id="Tea" />
}
```

**Comment by OvermindDL1** [comment]
> Using the Reason TEA example, I used the following code with the example code in order to create a ReasonReact element with TEA code for the logic, view etc. Is this the right way to do this? It works, but not sure how you'd send React props to the element.

Looks fine, and as for sending prop 'updates' just send them via a message perhaps?  :-)

> By logging the interface object to the browser console I can call pushMsg to increment and decrement the counter successfully, but I'm not sure how to call it from within the ReasonML React component.

You'll need to store the program interface in the react component, don't forget to destroy it when the react component is destroyed too.  :-)

> Ended up solving the issue using the following. This isn't really an issue anymore, but maybe I can include this in some documentation somewhere? I know this repo isn't specific to Reason or ReasonReact though, but someone else might need to do something similar.

I'd think that would be awesome!  I don't use React but documenting this could help others!  Maybe the wiki?  Although perhaps a `doc` directory in the repository itself, it needs to be started anyway and just getting the information in there 'now' is the important bit, can be formatted later, if you want to PR it in?  :-)

**Comment by BenSchZA** [comment]
Thanks for the feedback! I'll definitely add the above into a MD file in the doc directory, and add in a method to destroy the instance when the React component is destroyed.

**Comment by OvermindDL1** [comment]
Awesome!! I look forward to it from one who knows React!  :-)

**Comment by BenSchZA** [comment]
Knows React, but is very much new to OCaml/Reason! :) Just created the PR #122
