### ISSUE TITLE
Routing without Hash

### ISSUE THREAD

**Issue by sconeyard** [OvermindDL1/bucklescript-tea#128]
I'd like to build a SPA with bs-tea, however I can only get routes with the "#" prefix to work. Looking at ELM it should be possible to actually do routing on normal urls, however bs-tea lacks a linkClicked message. Is this feature in the works already or what steps are necessary to introduce this. 

Update: Found the onWithOptions method, which allows to prevent the default behavior for urls, therefore I could rebuild the desired behavior.

**Comment by OvermindDL1** [comment]
> Update: Found the onWithOptions method, which allows to prevent the default behavior for urls, therefore I could rebuild the desired behavior.

Yep, that's the purpose of it.  :-)

If something is common enough that you think it should be added as a helper, feel free to submit a PR!
