### ISSUE TITLE
input field not being updated correctly

### ISSUE THREAD

**Issue by martindemello** [OvermindDL1/bucklescript-tea#129]
If I try the following code:
```
let keypress_fn v =
  "hello"

let view model =
  div
    []
    [ span
        [ style "font-weight" "bold" ]
        [ text ("hello: " ^ model.current_word) ]
    ; br []
    ; input' [ type' "text"
             ; value model.current_word
             ; onInput ~key:"" (fun v -> CurrentWord (keypress_fn v))
             ; onCB "keyup" "" enter_fn
             ] []
    ]
````
(where returning `CurrentWord x` updates `model.current_word` as expected; full code at https://github.com/martindemello/bsinput)

the first time I hit a key, the input box does change to `hello`, but after that new keystrokes continue to show up in the box. `model.current_word` stays at `hello`, so I suspect the input field itself is not being updated.

**Comment by OvermindDL1** [comment]
Yep, onkeydown acquires before the textbox update, oninput does it after update, normal HTML5.  :-)
