### ISSUE TITLE
Failed to build bucklescript-tea on bs-platform 1.5.2

### ISSUE THREAD

**Issue by jackalcooper** [OvermindDL1/bucklescript-tea#18]
```
[1/15] Building src/tea_cmd.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_cmd.js src/tea_cmd.cmi
[2/15] Building src/tea_sub.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_sub.js src/tea_sub.cmi
[3/15] Building src/tea_json.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_json.js src/tea_json.cmi
FAILED: src/tea_json.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_json.js src/tea_json.cmi 
/Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bs-platform/bin/bsc.exe -bs-package-name bucklescript-tea  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src  -nostdlib -I /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bs-platform/lib/ocaml -bs-cross-module-opt -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/tea_json.mlast -c  src/tea_json.mlast 
File "/Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/src/tea_json.ml", line 118, characters 43-62:
Error: This expression has type 'a Js.Undefined.t -> 'a option
       but an expression was expected of type Web.Json.t option -> 'b
       Type 'a Js.Undefined.t = 'a Js.undefined is not compatible with type
         Web.Json.t option 
[4/15] Building src/tea_svg_attributes.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_svg_attributes.js src/tea_svg_attributes.cmi
[5/15] Building src/tea_html_cmds.cmj /Users/jackalcooper/elixir/subway_umbrella/apps/subway/node_modules/bucklescript-tea/lib/js/src/tea_html_cmds.js src/tea_html_cmds.cmi
```

**Comment by OvermindDL1** [comment]
Yep, 1.5.2 has had a substantial change in its API and is not a minor change (I wish it had a full version bump, it is not semver ^.^).

For now stick with 1.5.1 or earlier, I'll be updating tea when I get time (unless you want to fix it for me and PR?  :-) ).  :-)

I'll leave this up until it is updated.

**Comment by jackalcooper** [comment]
Yeah, I'm trying to and still at the stage getting familiar with the types 😄

**Comment by OvermindDL1** [comment]
> Yeah, I'm trying to and still at the stage getting familiar with the types 😄

Heh, a great way to learn HM-Typing is to make a mini-language that uses it, I've done that many times in various styles.  ^.^

At least if you know it compiles then it usually works.  ^.^

**Comment by bobzhang** [comment]
I already sent u the pr and it got merged?

**Comment by bobzhang** [comment]
Maybe you only need publish it?

**Comment by OvermindDL1** [comment]
> I already sent u the pr and it got merged?
> Maybe you only need publish it?

Ah it is the same file.

I'd not published yet because I was intending to go over all the other uses of undefined to see if there were others I should fix.  ^.^

I'll go ahead and publish so @jackalcooper can test if anything else.  :-)

And done, 0.2.5 published.

**Comment by jackalcooper** [comment]
It works now. Now there is only warning.

**Comment by jackalcooper** [comment]
This reappears... Now I think it's not caused by babel
![image](https://cloud.githubusercontent.com/assets/5133557/23910411/9f7fe20c-0914-11e7-8c61-2b7dd34b06d1.png)
![image](https://cloud.githubusercontent.com/assets/5133557/23910433/af36f456-0914-11e7-915a-ef373bfd7a5a.png)

**Comment by bobzhang** [comment]
@jackalcooper are you aware of changes in 1.5.0 ? (I think your last revision is 1.4.0) http://bloomberg.github.io/bucklescript/Manual#_object_label_translation_convention
it seems you need `x._open` and `x.send__string` if you need overriding, we will keep changes as minimal as possible in the future, sorry for the inconvenience

**Comment by jackalcooper** [comment]
I'm going to open another issue for this.

**Comment by jackalcooper** [comment]
https://github.com/OvermindDL1/bucklescript-tea/issues/19
