### ISSUE TITLE
Failed to switch to the npm release from testing project

### ISSUE THREAD

**Issue by jackalcooper** [OvermindDL1/bucklescript-tea#2]
I got this:
```
File "_none_", line 1, characters 0-0:
Error: Package bucklescript-tea not found or bucklescript-tea/lib/ocaml does not exist or please set npm_config_prefix correctly
ninja: build stopped: subcommand failed.

```
package.json:
```
{
  "repository": {},
  "engine": "node 6.0.0",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin",
    "assets:clean": "rm -rf public/assets",
    "postinstall": "npm run deploy"
  },
  "dependencies": {
    "bucklescript-tea": "^0.1.1"
  },
  "devDependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "2.7.4",
    "clean-css-brunch": "~2.0.0",
    "css-brunch": "~2.0.0",
    "javascript-brunch": "~2.0.0",
    "uglify-js-brunch": "~2.0.1",
    "bs-platform": "^1.2.0",
    "jquery": ">= 2.1"
  }
}
```
bsconfig.json:
```
{
    "name" : "trash_talk",
    "version": "0.0.1",
    "bs-dependencies" : ["bucklescript-tea"],
    "sources" : [
         { "dir" :  "app/bucklescript/trash_talk"}
        ],
    "bsc-flags": ["-bin-annot"],
    "generate-merlin" : true
}
```

**Comment by OvermindDL1** [comment]
I used your above files and created an empty file in `app/bucklescript/trash_talk` of `main_entry.ml` then ran `./node_modules/.bin/bsb` and got the same error:
```sh
$ ./node_modules/.bin/bsb
lib\bs\.bsdeps does not exist
Regenrating build spec
Failure("bucklescript-tea not found when resolving dependecies")
```

I might have made it wrong, but this really looks more to me as a bug in bsb (I think `bucklescript-tea` is the first 'library' on bucklescript that uses bsb?).  @bobzhang any thoughts?  What did I break?

**Comment by bobzhang** [comment]
it is probably a bsb bug, I will have a look.
but you need `bsb -make-world -w  ` here to build bucklescript-tea first

**Comment by bobzhang** [comment]
I will add BuckleScript tea into integration test for next release stay tuned

**Comment by jackalcooper** [comment]
@bobzhang Just out of curiosity how long does your integration test take now? I listened to the 代码时间 podcast you were in and you said it was blazingly fast.

**Comment by jackalcooper** [comment]
Same error when I run `bsb -make-world -w`

**Comment by bobzhang** [comment]
it is Chinese New Year, slow days... I think we can get the new release out of the door next week

**Comment by OvermindDL1** [comment]
> it is Chinese New Year, slow days... I think we can get the new release out of the door next week

Not something I borked?  Good to hear.  ^.^;

**Comment by bobzhang** [comment]
@OvermindDL1 it works on my machine now! I enjoy tea, and I like bucklescript-tea even better, will send you a pull request!

**Comment by OvermindDL1** [comment]
> @OvermindDL1 it works on my machine now! I enjoy tea, and I like bucklescript-tea even better, will send you a pull request!

Awesome!  Be sure to bump the bs-platform required version in the package.json or move it to peer/optional dependencies with the right working version, depending on how you want the library being worked with, I want to follow the standards you want to impose as much as possible.  :-)

**Comment by OvermindDL1** [comment]
@bobzhang Also my last few blog entries at http://blog.overminddl1.com/ have been bucklescript, I've been delaying putting up my partially-complete bucklescript-tea one until this has an easy and confirmed installation method that is pretty well 'ratified' by you if you'd be interested in seeing it before I post (which I can finish it for you to see once I get an example project built and working on this :-) ).

**Comment by OvermindDL1** [comment]
It seems the latest version of Bucklescript has resolved this issue, so closing this case.  Please comment again here if further issues, and do remember to fully rebuild on new bucklescript versions.  :-)

**Comment by jackalcooper** [comment]
Yes, it works fine now😄
