### ISSUE TITLE
Bucklescript deprecations

### ISSUE THREAD

**Issue by OvermindDL1** [OvermindDL1/bucklescript-tea#31]
Recently Bucklescript has deprecated some functions without a major version bump as per NPM semver, which caused this library to break on its depended on version of bs-platform.  There are more deprections and other various warnings, these should be fixed pro-actively before bs-platform removes them since a major version bump does not seem to happen as per NPM semver requirements for backwards-incompatible API changes (Please change that since Bucklescript is distributed via NPM ^.^).

**Comment by OvermindDL1** [comment]
Assigned to @jackalcooper as per: https://github.com/OvermindDL1/bucklescript-tea/pull/30#issuecomment-308792279

**Comment by tcoopman** [comment]
This can be closed, no? By #32?

**Comment by OvermindDL1** [comment]
@tcoopman Heh, yes indeed.  ^.^
