### ISSUE TITLE
`onWithOptions` is missing

### ISSUE THREAD

**Issue by tcoopman** [OvermindDL1/bucklescript-tea#37]
Title says it all (http://package.elm-lang.org/packages/evancz/elm-html/4.0.0/Html-Events#onWithOptions).
I would create a PR, but the vdom stuff about `onCB` and `onMsg` is not completely clear to me.

**Comment by OvermindDL1** [comment]
Yeah I always meant to add it, been working on the event directly in the main callback currently as a more direct work-around...  >.>

Leaving this open until added.  :-)

**Comment by tcoopman** [comment]
That pointer was sufficient to fix my problem. If anyone else wants the same:

```ocaml
        button [onCB "click" "someKey" (fun event -> 
          event##preventDefault () |> ignore;
          event##stopPropagation () |> ignore;
          Some Msg)
        ] [...]
```

**Comment by OvermindDL1** [comment]
Whoo right!  This one can be closed now!  :-)
