### ISSUE TITLE
Cannot apply node without optional arguments

### ISSUE THREAD

**Issue by copy** [OvermindDL1/bucklescript-tea#39]
`Tea_html.node` is defined as follows:

```ocaml
let node ?(namespace="") tagName ?(key="") ?(unique="") props nodes = fullnode namespace tagName key unique props nodes
```

Correct me if I'm wrong, but since the optional parameters come after a normal parameter, it's impossible to apply this function without the latter two optional parameters.

**Comment by OvermindDL1** [comment]
> Correct me if I'm wrong, but since the optional parameters come after a normal parameter, it's impossible to apply this function without the latter two optional parameters.

That is wrong.  ^.^

Optional arguments in OCaml as in most decent languages are short-circuiting as they have to be named to be used.  Give it a try, the examples and other projects all work fine.  :-)

**Comment by copy** [comment]
You're right, of course. I misinterpreted the error message ("... cannot be applied without label"). Apologies for the noise.

**Comment by OvermindDL1** [comment]
> You're right, of course. I misinterpreted the error message ("... cannot be applied without label"). Apologies for the noise.

No worry, good to test things regardless.  :-)
