### ISSUE TITLE
Bug related to `noProp`

### ISSUE THREAD

**Issue by bcc32** [OvermindDL1/bucklescript-tea#43]
I created a test at bcc32/bucklescript-tea@acc15ec08e29ea9d53727f16c31857298a1f138e.

When a vdom property is given a non-trivial value and is then changed to
`noProp`, the attribute ends up having as value the string "undefined". For the
example added in this commit, the element might end up looking like:

```html
<li lang="undefined" style="color: blue;">Ocaml</li>
```

I ran into this bug when I was adding and removing the `href` attribute from an `<a>`, which meant that clicking on the link redirected the browser to the (relative) URL "undefined", rather than doing nothing as expected.

**Comment by OvermindDL1** [comment]
Checking...

It is getting set to that when it is removed, the 'lang' type is of `Vdom.prop "lang"`, which is of type `RawProp`, which is removed via `Web.Node.setProp elem k Js.Undefined.empty`, which is just doing `elem['lang'] = undefined;` in javascript, which seems correct for properties.  Not seeing any issue there.  However checking the HTML spec shows that the `lang` you seem to be trying to set is an `attribute`, not a property, and thus by using the `Vdom.prop "lang"` you are declaring it as a property, when you should be using `Vdom.attribute "" "lang"` (empty namespace in the HTML spec), and by changing the test to that here locally, then it works fine.  :-)

So it is not a bug, just part of the stupidity of how the DOM works.  ^.^;

In general, if you see anything getting mis-set like that, usually good to check the HTML spec first to make sure if it is an attribute or a property and be sure to use the correct one.  There is no easy or fast way to check it via code sadly.

Thanks much though, this reminds me that I need to add more documentation about that and checking the spec to use the right type.  Any VDom implementation is similar, it is related to the real DOM, not a VDom.  :-)

**Comment by bcc32** [comment]
Ok, I think I more or less understand the explanation, although I still need to brush up . I was having trouble with the `Tea_html.href` property, so that should be changed to be an attribute instead?

**Comment by OvermindDL1** [comment]
> I was having trouble with the Tea_html.href property, so that should be changed to be an attribute instead?

Heh, if it is then yeah, it probably should...  ^.^
It'll be changed in the next version.  I should move it to the `Attributes` area, I'll copy it there for now and remove it later at some major version change, both will work though at the next minor update regardless.  ^.^;
Hmm, looks like Elm has it wrong too, blehg, I'll have to keep it in this namespace then for compat with it...
And published, update it and try again?  :-)

**Comment by bcc32** [comment]
Great. Looks like it's working for me. Re: Elm, I don't remember elm-lang/html having anything like `noProp` at all, you'd just have to change the length of the list.

**Comment by OvermindDL1** [comment]
> I don't remember elm-lang/html having anything like noProp at all, you'd just have to change the length of the list.

It doesn't, though you could kind-of make one yourself by just binding something unused, like `blah` to the empty string.  It would still be less efficient that my native noProp though as it is truly a no-op on the DOM.  You could still hit the issue in Elm if the DOM attributes were ordered in 'just' the wrong way.
