### ISSUE TITLE
Is it possible to insert a div created in javascript in my view function

### ISSUE THREAD

**Issue by tcoopman** [OvermindDL1/bucklescript-tea#51]
Basically, can I do something like this?

```ocaml
type document
type element
external document : document = "" [@@bs.val]
external createElement : document -> string -> element = "" [@@bs.send]

view _ =
  let elem = createElement document "div"
  div [] [elem]
```

The reason for this is that I use a library (esri api) that attaches itself to a htmlElement. So if I create the element and then pass it, the library works, but now I want to also render that element in my app, and I don't know how to do that.

**Comment by OvermindDL1** [comment]
Easiest way would be to give your div in your view an id (something like `div [id "blah"] []` then use javascript to link that external element to the element with that id.  Do note, the vdom can entirely wipe the actual dom if structural changes happen, so as long as you keep the structure the same then all should be good.

For note, in the future this will be pretty trivially easy to do once I refactor the vdom and add support for custom elements.  You'll be able to add in other elements from other libraries with ease then, for now it is about as hard to do as it is in Elm itself.  ^.^;

**Comment by jackalcooper** [comment]
I think this use case is quite common. For instance, plotting with a
JavaScript library using the data managed by TEA was what I encountered. It
will be another big plus for TEA and BuckleScript if this feature is added
since the JavaScript support has already been there.

**Comment by OvermindDL1** [comment]
Yep, entirely planned.  ^.^

Right now you just have to do it the same way you'd to it in Elm as I mimicked it too closely in this version, but my custom managed nodes will have that fixed.  :-)

This is technically a duplicate of #40 as they have the same resolution.  :-)
