### ISSUE TITLE
Router Support (SPA)

### ISSUE THREAD

**Issue by WolfDan** [OvermindDL1/bucklescript-tea#63]
Elm have support for SPA, it can be creat if bucklescript does the same

Basically is give support to a Router (and SSR as complement)

**Comment by tcoopman** [comment]
What would you expect of support for a router? I don't see why you couldn't pick a js router and use that one in your project or use bindings to the html5 history api?

**Comment by WolfDan** [comment]
Is more related to the SSR side (as I understand to do this correctly you need to parse the routes too, correct me if I'm wrong)

**Comment by OvermindDL1** [comment]
Also the `Tea.Navigation` module can already control and respond to route changes, it is Elm's version of a router and it's API is duplicated here (although in Elm it is a secondary library).  It contains the primitives so you can easily built a more powerful one as well.  :-)

So, doesn't this already exist?

**Comment by WolfDan** [comment]
Oh my fault! I didn't notice it (I was checking all from the examples so I thought it was not implemented) 

I think the library need documentation and more examples ^^ 

I'll close the issue :)

**Comment by tcoopman** [comment]
I didn't know this either. Nice!

**Comment by OvermindDL1** [comment]
Hah, awesome.  Yeah it was a common Elm function that I needed for my own work, hence why it was added in early.  ^.^

**Comment by OvermindDL1** [comment]
And yes, docs are needed, though for now you can use Elm docs, it is almost identical (API should be about the same, syntax is just OCaml'y, which is barely different from Elm ^.^).  :-)
