### ISSUE TITLE
I made another starter kit

### ISSUE THREAD

**Issue by feluxe** [OvermindDL1/bucklescript-tea#69]
Hi there,

I created a starter kit that uses:

* Reason Syntax
* Webpack 4
* [bs-css](https://github.com/SentiaAnalytics/bs-css)

https://github.com/feluxe/bs-tea-starter-kit

Took me some time to get this running and I guess it might be valuable for other newcomers.

Please leave an issue/PR if you think it needs improvement.

Could this be added to the "Starter-Kit" section in the README?

Cheers! :)

**Comment by OvermindDL1** [comment]
> Could this be added to the "Starter-Kit" section in the README?

Definitely!  Submit a PR for it!  And don't forget to add yourself to the contributors list.  :-)
