### ISSUE TITLE
improve the performance and code size using belt?

### ISSUE THREAD

**Issue by bobzhang** [OvermindDL1/bucklescript-tea#73]
As you may know that we published an experimental stdlib which is optimized for performance and size. BuckleScript-Tea is purely OCaml, so the benefit would trickle down naturally, I wonder what's your opinion on this issue?

Pro: Better performance and smaller size, the generated code is also easier to debug

Con: The only con that I have in mind is belt is not on native yet(it is on our road map once it reaches some stability), but as a front-end library, I think it does not matter that much. SSR on nodejs is more natural than ocaml native since there are plenty of existing web servers already in NodeJS (I know OCamlOpt is much nicer, but the reality is NodeJS is running everywhere)

**Comment by OvermindDL1** [comment]
I love performance!  As long as it works via the native compiler as well for server-sided generation to work then I am all for it!  :-)

**Comment by jackalcooper** [comment]
@OvermindDL1 could you write a blog post about how to do this right?

> OCaml would not be doing the web hosting, it gets plugged into the BEAM VM via C interfaces. 

 I tried to do so and failed miserably 😢.

**Comment by jackalcooper** [comment]
> /me still doesn't understand what would possess someone to want to run a web server in javascript of all things

If all the services are containerized and Kubernetes replicates them? Well it would take much more efforts to achieve Erlang class fault tolerance. I will not considering using node either if there is no robust container infrastructure.

**Comment by bobzhang** [comment]
There are multi-billion dollar business involved in Node, it does not really make sense to ignore it

**Comment by OvermindDL1** [comment]
> There are multi-billion dollar business involved in Node, it does not really make sense to ignore it

Hence why it would still be supported, but it *absolutely* should not be mandated.  Native code is an absolute necessity where I work.

Also, multi-billion dollar businesses use PHP and ASP (the old versions, the later ASP.NET versions are significantly better, though still not something I'd want to use), still doesn't make them good or appropriate.  ;-)
