### ISSUE TITLE
Matching elm APIs

### ISSUE THREAD

**Issue by neochrome** [OvermindDL1/bucklescript-tea#78]
Hi,
I just thought I should ask what is the goal regarding matching the elm APIs?
I noted that for instance the Html module currently doesn't follow the elm-html module v2.0.0 with regards to how things are arranged by sub modules.
Is this something that should be considered to be updated to be more like the elm APIs, although it would be a breaking change?

**Comment by OvermindDL1** [comment]
The latest Elm API has had major changes so I'm currently sticking to a slightly older version.

*However*, I am thinking of just versioning parts of the API as the back-end should remain the same anyway.  If you want to start making a versioned api that can just be `open`ed then used similar to Elm, that's a PR that would be awesome!  :-)

This project is planned to have a variety of interfaces though, one big one is I want to get a webcomponent style one made, though the spec is soooo slow-coming, I keep waiting and hoping for stability with it...

I do want to try to keep backwards compatibility though, just add 'newer' API's via new modules.  :-)

**Comment by neochrome** [comment]
> However, I am thinking of just versioning parts of the API as the back-end should remain the same anyway. If you want to start making a versioned api that can just be opened then used similar to Elm, that's a PR that would be awesome! :-)

I'll see if I can get something cooking...

> I do want to try to keep backwards compatibility though, just add 'newer' API's via new modules. :-)

Sounds like great way forward which would allow following the elm APIs quite close!

**Comment by OvermindDL1** [comment]
Especially as Elm's core API breaks every-single-version...  ^.^;

**Comment by neochrome** [comment]
I'm making some good progress on the html module.
I found that elm-html doesn't have all available tags/elements - should I put those next to the existing or in some Ext sub module or something?

**Comment by neochrome** [comment]
What about something like this?
https://github.com/OvermindDL1/bucklescript-tea/compare/master...neochrome:elm-html2-compliant?expand=1

**Comment by neochrome** [comment]
I actually think that Html2 is more correct, since it's only the elm-compiler that has version 0.18 - all other parts are in separately versioned modules.

The biggest differences are the structuring into sub modules for Attributes, Events etc. Also there are additional tags/attributes in the elm-html@2.0.0.

**Comment by OvermindDL1** [comment]
Ah true, perhaps match it to the version of the HTML library in elm then as I know they have distinct versioning?  :-)

> The biggest differences are the structuring into sub modules for Attributes, Events etc. Also there are additional tags/attributes in the elm-html@2.0.0.

Cool, thanks.  :-)

**Comment by neochrome** [comment]
> Ah true, perhaps match it to the version of the HTML library in elm then as I know they have distinct versioning? :-)

That was my intention with the added number 2 :-)
Maybe it's enough to use only the major version, since minor and revision can't have breaking changes in elm? And just update the corresponding major version module with minor/revision changes as needed?

**Comment by OvermindDL1** [comment]
I'd just use the major version number yeah.  Revision should just be patches and minor is just feature additions that are backwards compatible, so that should be entirely fine.  :-)

**Comment by neochrome** [comment]
Regarding `including` the existing `Html` module for reuse - sounds like a good idea, but then the "public" api of the new module will have things like `Events` mixed with tags/elements etc, unless a .mli-file is introduced which only exposes the relevant parts.
Another way would be to "pass through" functions like: `let div = Html.div` and so on, however I don't know how much is actually reused that way - I mean, the functions in the html module(s) are pretty much just mappings of function name to tag name.
Any takes on how to proceed?

**Comment by OvermindDL1** [comment]
Yeah an mli file could be used to remove it, but then that does end up about duplicating it anyway, so I guess it doesn't matter.  ^.^;

Eh, copying is fine then, it all goes down to the Vdom calls anyway.  :-)

**Comment by OvermindDL1** [comment]
Pre-mature at this point I'd think, these are all generically useful things and even if someone doesn't use a module then rollup and such things will prune it anyway.  :-)

**Comment by neochrome** [comment]
Created a pull request #82 for this now :)
