### ISSUE TITLE
[discussion] Debugging similar to Elm

### ISSUE THREAD

**Issue by neochrome** [OvermindDL1/bucklescript-tea#83]
So, I've been working a bit on a simple "time travel debugger" like the one in Elm.
A small demo is available at https://neochrome.github.io/debug2/

Example usage:
```ocaml
let () =
  let module D = Debug.Make(struct
    type flags = unit
    type msg = my_msg
    type model = my_model
    let init = init
    let update = update
    let view = view
    let subscriptions = subscriptions
    let string_of_msg = function
      | Increment -> "Increment"
      | Decrement -> "Decrement"
      | Reset -> "Reset"
      | Set _ -> "Set"
  end) in
  D.standardProgram (Web.Document.getElementById "main") () |> ignore;;
```

Is this something that would be of interest to include in the core `bucklescript-tea` package or is better off as a peer package that might be added if needed?

Your thoughts?

**Comment by OvermindDL1** [comment]
I think it would be awesome to include it personally!  But if you want to keep it as a side project that's entirely fine too (I can link to it), though if you want to include it then I can mark that code as owned by you and give you commit access.  :-)

**Comment by OvermindDL1** [comment]
Javascript bundlers are excellent at removing code that is not used, so I really don't see the issue at including useful things like this.  :-)

**Comment by OvermindDL1** [comment]
Also I love the module interface (much more traditionally 'OCamly'), and I *do* want to use the module interface for later incarnations of this project, but any chance you could use records with functions like Elm does as well thus making it more trivial to convert someone's project to use the debugger and back again?  That way they'd only need to decorate a single call instead of rewriting the entire main area?  :-)

**Comment by neochrome** [comment]
Awesome, then I'll prepare a PR!

> I can mark that code as owned by you and give you commit access. :-)

Thanks. What ever is easiest for you, I'm good either way :-)

> but any chance you could use records with functions like Elm

I'd love to have both as well, but I think I need some help to get the types right with the record approach...

**Comment by OvermindDL1** [comment]
> I'd love to have both as well, but I think I need some help to get the types right with the record approach...

Sure, show the code and errors (like via the PR if that is easiest) and I can fix it.  :-)

**Comment by neochrome** [comment]
PR #84 created as to show off initial implementation and usage as of now.
This should be iterated over and expanded with support for `beginnerProgram` etc before done I think.

Will update with my attempt at record-based usage as well.

**Comment by neochrome** [comment]
I'll close this since the PR is merged and all :-)
